version: '2.1'

services:
  simpleserver:
    image: simpleserver
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 10001:10001
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 server.js